### ISSUE TITLE
--submenu-item-fill is never applied

### ISSUE THREAD

**Issue by Kaijun** [ElementUI/theme-default#11]
I didn't find any `--submenu-item-fill` references in `theme-default` 

menu css src: https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/menu.css

variable: https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/common/var.css#L524

**Comment by Leopoldthecoder** [comment]
Looks it's redundant. I'll remove it.

**Comment by Kaijun** [comment]
删除是指的是不在有地方配置 --submenu-item-fill 吗？

**Comment by Leopoldthecoder** [comment]
对，把这个变量删掉了。

**Comment by Kaijun** [comment]
@Leopoldthecoder 但是可以配置 `--menu-item-fill` 却不能配置 `--submenu-item-fill` 的话有点奇怪

**Comment by Leopoldthecoder** [comment]
哦，那你可以看看在需要配置的地方加一下，给我们提个 PR。

**Comment by Kaijun** [comment]
@Leopoldthecoder OK
