### ISSUE TITLE
Consider sass/scss format for source files

### ISSUE THREAD

**Issue by dariuszsikorski** [ElementUI/theme-default#22]
Hello, after quick read of source I noticed the theme is using Css4 standard, which at current moment has to be compiled to regular Css through some preprocessor. Many application frameworks are configured to compile Sass files. Using Css4 files to create customized theme requires extra-setup for each project.

I would suggest migrating to Sass at the moment or developing parallel version in 'src-sass' folder.
Anyway, ElementUi is by far the biggest Vue ui library and you guys did a lot of good work!

**[update]** Realised it's not CSS4, but Sass + PostCss

**Comment by Leopoldthecoder** [comment]
Our team has discussed this and it's already on our roadmap.

**Comment by dariuszsikorski** [comment]
Thanks for the clarification.
