### ISSUE TITLE
生成的css不纯

### ISSUE THREAD

**Issue by GoDotDotDot** [ElementUI/theme-default#28]
当我使用`element-theme` 编译生成css样式表时，发现生成对应组件的css里面又包含了其他组件的样式表。比如`table`组件的样式表包含了`checkbox`的样式表，原因可能是table组件导入了checkbox组件。
我期望的是生成的样式表单一，只生产自己组件的样式，不要包含其他组件的样式表。

因为我目前的做法是为每个组件直接`import` 他自己的样式表，webpack在打包的时候会自动导入引用的组件的样式表，我这样做为了方便维护组件。

示例：
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Component, PropTypes } from '../../../libs';
import { enhanceColumns, calculateFixedWidth, scheduleLayout } from './mixins';
import { getScrollBarWidth } from './utils';
import TableHeader from './TableHeader';
import TableBody from './TableBody';
import TableFooter from './TableFooter';
import i18n from '../locale';

import type {
  TableProps,
  TableState,
  DefaultTableProps
} from './Types';
// 下面这句是导入的element-theme编译生成的css
import '../theme/table.css'
```

但是这个table.css文件里面包含了CheckBox的样式表，有没有办法让table.css被编译时只保留Table组件的样式表。而不用自己去手动更改table.css里面多余的其他组件的样式？

**Comment by Leopoldthecoder** [comment]
> 只生产自己组件的样式，不要包含其他组件的样式表
 
有什么具体原因需要这样吗？

**Comment by GoDotDotDot** [comment]
@Leopoldthecoder 因为我目的是想把每个组件的样式表放到各自的组件目录下，单独维护。比如上面的代码，在table组件中，引入了table.css样式表，但是目前这个样式表里面包含了checkbox样式表。这就会出现一个问题，比如我一个页面同时使用了checkbox组件和table组件的时候，打包出来的css就是`table.css`和`checkbox.css`的组合体，就会出现`checkbox`的样式重复问题，究其原因应该是`table.css`里面包含了`checkbox`的样式表。

所以我的想法是`table`组件只包含自身的样式，这样不管你引入了多少组件，最后的css样式表都不会重复。

**Comment by Leopoldthecoder** [comment]
如果组件的样式不把它依赖的样式引进来的话，就需要用户自己去引， 但是用户是不了解某个组件依赖了哪些组件的。

如果比较在意打包后的体积，可以在打包时使用去重的 CSS 插件，比如 [uncss](https://www.npmjs.com/package/uncss)

**Comment by GoDotDotDot** [comment]
@Leopoldthecoder 其实也不需要自己去引，只要检测到依赖关系都会打包的，我 就使用去重插件去重吧。谢谢你
