### ISSUE TITLE
Some icons like el-icon-info are not showed

### ISSUE THREAD

**Issue by NachE** [ElementUI/theme-default#34]
Some icons referenced [in documentation](http://element.eleme.io/#/en-US/component/icon) like el-icon-info are not showed. Instead of icon print, nothing appears.

Using [theme-chalk](https://github.com/ElementUI/theme-chalk) (apparently used in the documentation) all icons works fine.

**Comment by Leopoldthecoder** [comment]
For theme-default, you need to check the 1.4.* docs.
