### ISSUE TITLE
编译主题时提示找不到 vue-popup/lib/popup.css

### ISSUE THREAD

**Issue by aNd1coder** [ElementUI/theme-default#6]
**版本说明**
`"element-ui": "^1.0.2"`
`"element-theme": "^0.2.0"`
`"element-theme-default": "^1.0.2"`

执行 `node_modules/.bin/et` 命令时报错提示：
``
Error: ENOENT: no such file or directory, open 'xxx/node_modules/element-theme-default/src/vue-popup/lib/popup.css'
``

**Comment by aNd1coder** [comment]
越墙重新安装了下没问题，这个 issue 可以关闭了

**Comment by wucuida** [comment]
我也遇到了相同的问题，根本没有找到vue-popup/lib/popup.css这个文件

**Comment by reverland** [comment]
@wucuida 依赖里有写，先npm install

**Comment by chertpong** [comment]
I also found this problem. Did anyone solve this?

**Comment by ab-su-rd** [comment]
for a workaround, you can copy vue-popup into element-theme-default/src and the build works.

**Comment by chertpong** [comment]
@ab-su-rd thanks! that's work.

**Comment by yinshipeng** [comment]
从node_modules下找到vue-popup文件夹复制到element-theme-default/src下就可以了。

**Comment by QingWei-Li** [comment]
fixed via https://github.com/ElemeFE/postcss-salad/commit/1c895a260ee683079092c0225ecf233b813d79ae
