### ISSUE TITLE
Cannot change border-radius style of Input with custom-style

### ISSUE THREAD

**Issue by espspinix** [ElementUI/theme-default#9]
Hello,
I cannot change the border-radius with the theme tool for the input elements, as described in the docs: http://element.eleme.io/#/en-US/component/custom-theme

I guess the problem is, that the border-radius is fixed in the following lines:

https://github.com/ElementUI/theme-default/blob/master/src/input.css#L15
https://github.com/ElementUI/theme-default/blob/master/src/input.css#L123
https://github.com/ElementUI/theme-default/blob/master/src/input.css#L190

Should be fixed by replacing those lines to:
`border-radius: var(--button-border-radius);`

Thanks,
Philipp

**Comment by Leopoldthecoder** [comment]
@mklemenz helped fix this in https://github.com/ElemeFE/element/pull/2918
